-- FILE: 000002_init.down.sql

ALTER TABLE organization
ALTER COLUMN createdAt DROP DEFAULT;

ALTER TABLE shelter
ALTER COLUMN createdAt DROP DEFAULT,
ALTER COLUMN refugeesCount DROP DEFAULT,
ALTER COLUMN contactPhone DROP NOT NULL,
ALTER COLUMN contactEmail DROP NOT NULL;

ALTER TABLE refugee
ALTER COLUMN createdAt DROP DEFAULT,
ALTER COLUMN age DROP DEFAULT;