INSERT INTO cities (name) VALUES
('Bogotá'),
('Medellín'),
('Cali'),
('Barranquilla'),
('Cartagena'),
('Cúcuta'),
('Bucaramanga'),
('Pereira'),
('Santa Marta'),
('Ibagué'),
('Manizales'),
('Villavicencio'),
('Pasto'),
('Montería'),
('Neiva'),
('Armenia'),
('Popayán'),
('Sincelejo'),
('Valledupar'),
('Tunja'),
('Florencia'),
('Riohacha'),
('Quibdó'),
('Mocoa'),
('San Andrés'),
('Leticia'),
('Yopal'),
('Inírida'),
('Mitú'),
('Puerto Carreño');