ALTER TABLE organization
ALTER COLUMN createdAt SET DEFAULT CURRENT_DATE;

ALTER TABLE shelter
ALTER COLUMN createdAt SET DEFAULT CURRENT_DATE,
ALTER COLUMN refugeesCount SET DEFAULT 0,
ALTER COLUMN contactPhone SET NOT NULL,
ALTER COLUMN contactEmail SET NOT NULL;

ALTER TABLE refugee
ALTER COLUMN createdAt SET DEFAULT CURRENT_DATE,
ALTER COLUMN age SET DEFAULT 0;